// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "game_common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocols {
namespace common {

namespace {

const ::google::protobuf::EnumDescriptor* MessageModule_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MessageType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ItemPositionType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* DirectionType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MessageAction_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ARENA_PUBLIC_NOTICE_TYPE_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* PUBLIC_NOTICE_TYPE_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* Profession_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* Gender_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* GameStatus_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* AccountStatus_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_game_5fcommon_2eproto() {
  protobuf_AddDesc_game_5fcommon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "game_common.proto");
  GOOGLE_CHECK(file != NULL);
  MessageModule_descriptor_ = file->enum_type(0);
  MessageType_descriptor_ = file->enum_type(1);
  ItemPositionType_descriptor_ = file->enum_type(2);
  DirectionType_descriptor_ = file->enum_type(3);
  MessageAction_descriptor_ = file->enum_type(4);
  ARENA_PUBLIC_NOTICE_TYPE_descriptor_ = file->enum_type(5);
  PUBLIC_NOTICE_TYPE_descriptor_ = file->enum_type(6);
  Profession_descriptor_ = file->enum_type(7);
  Gender_descriptor_ = file->enum_type(8);
  GameStatus_descriptor_ = file->enum_type(9);
  AccountStatus_descriptor_ = file->enum_type(10);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_game_5fcommon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_game_5fcommon_2eproto() {
}

void protobuf_AddDesc_game_5fcommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protocols::common::protobuf_AddDesc_error_5fcode_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021game_common.proto\022\020protocols.common\032\020e"
    "rror_code.proto*;\n\rMessageModule\022\023\n\017MSG_"
    "MODULE_GAME\020\000\022\025\n\021MSG_MODULE_SERVER\020\017*O\n\013"
    "MessageType\022\024\n\020MSG_TYPE_REQUEST\020\000\022\025\n\021MSG"
    "_TYPE_RESPONSE\020\001\022\023\n\017MSG_TYPE_NOTIFY\020\002*N\n"
    "\020ItemPositionType\022\013\n\007IPT_BAG\020\000\022\r\n\tIPT_EQ"
    "UIP\020\001\022\r\n\tIPT_DEPOT\020\002\022\017\n\013IPT_BUYBACK\020\003*\236\001"
    "\n\rDirectionType\022\021\n\rDT_NORTH_WEST\020\004\022\014\n\010DT"
    "_NORTH\020\005\022\021\n\rDT_NORTH_EAST\020\006\022\013\n\007DT_WEST\020\003"
    "\022\013\n\007DT_SELF\020\000\022\013\n\007DT_EAST\020\007\022\021\n\rDT_SOUTH_W"
    "EST\020\002\022\014\n\010DT_SOUTH\020\001\022\021\n\rDT_SOUTH_EAST\020\010*,"
    "\n\rMessageAction\022\033\n\027MSG_ACTION_PLAYER_LOG"
    "IN\020\001*[\n\030ARENA_PUBLIC_NOTICE_TYPE\022\024\n\020AREN"
    "A_RANK_TOP_3\020\001\022\025\n\021ARENA_RANK_TOP_50\020\002\022\022\n"
    "\016ARENA_CONT_WIN\020\003*.\n\022PUBLIC_NOTICE_TYPE\022"
    "\030\n\024SYSTEM_PUBLIC_NOTICE\020\000*2\n\nProfession\022"
    "\n\n\006WIZARD\020\001\022\n\n\006ARCHER\020\002\022\014\n\010SWORDMAN\020\003*\036\n"
    "\006Gender\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\002*<\n\nGameSta"
    "tus\022\016\n\nGS_OFFLINE\020\000\022\r\n\tGS_ONLINE\020\001\022\017\n\013GS"
    "_FIGHTING\020\002*\257\001\n\rAccountStatus\022!\n\024Account"
    "Status_BANNED\020\377\377\377\377\377\377\377\377\377\001\022\031\n\025AccountStatu"
    "s_DEFAULT\020\000\022\037\n\033AccountStatus_FIRST_LOGIN"
    "ED\020\001\022\037\n\033AccountStatus_CREATING_ROLE\020\002\022\036\n"
    "\032AccountStatus_CREATED_ROLE\020\003", 949);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "game_common.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_game_5fcommon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_game_5fcommon_2eproto {
  StaticDescriptorInitializer_game_5fcommon_2eproto() {
    protobuf_AddDesc_game_5fcommon_2eproto();
  }
} static_descriptor_initializer_game_5fcommon_2eproto_;

const ::google::protobuf::EnumDescriptor* MessageModule_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageModule_descriptor_;
}
bool MessageModule_IsValid(int value) {
  switch(value) {
    case 0:
    case 15:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageType_descriptor_;
}
bool MessageType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ItemPositionType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ItemPositionType_descriptor_;
}
bool ItemPositionType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* DirectionType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DirectionType_descriptor_;
}
bool DirectionType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MessageAction_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageAction_descriptor_;
}
bool MessageAction_IsValid(int value) {
  switch(value) {
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ARENA_PUBLIC_NOTICE_TYPE_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ARENA_PUBLIC_NOTICE_TYPE_descriptor_;
}
bool ARENA_PUBLIC_NOTICE_TYPE_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* PUBLIC_NOTICE_TYPE_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PUBLIC_NOTICE_TYPE_descriptor_;
}
bool PUBLIC_NOTICE_TYPE_IsValid(int value) {
  switch(value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* Profession_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Profession_descriptor_;
}
bool Profession_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* Gender_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Gender_descriptor_;
}
bool Gender_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* GameStatus_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GameStatus_descriptor_;
}
bool GameStatus_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* AccountStatus_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AccountStatus_descriptor_;
}
bool AccountStatus_IsValid(int value) {
  switch(value) {
    case -1:
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace protocols

// @@protoc_insertion_point(global_scope)
