// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_client.proto

#ifndef PROTOBUF_game_5fclient_2eproto__INCLUDED
#define PROTOBUF_game_5fclient_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "game_common.pb.h"
// @@protoc_insertion_point(includes)

namespace protocols {
namespace common {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_game_5fclient_2eproto();
void protobuf_AssignDesc_game_5fclient_2eproto();
void protobuf_ShutdownFile_game_5fclient_2eproto();

class PlayerLoginRequest;
class PlayerLoginResponse;

// ===================================================================

class PlayerLoginRequest : public ::google::protobuf::Message {
 public:
  PlayerLoginRequest();
  virtual ~PlayerLoginRequest();
  
  PlayerLoginRequest(const PlayerLoginRequest& from);
  
  inline PlayerLoginRequest& operator=(const PlayerLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerLoginRequest& default_instance();
  
  void Swap(PlayerLoginRequest* other);
  
  // implements Message ----------------------------------------------
  
  PlayerLoginRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerLoginRequest& from);
  void MergeFrom(const PlayerLoginRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::int32 uid() const;
  inline void set_uid(::google::protobuf::int32 value);
  
  // required string pwd = 2;
  inline bool has_pwd() const;
  inline void clear_pwd();
  static const int kPwdFieldNumber = 2;
  inline const ::std::string& pwd() const;
  inline void set_pwd(const ::std::string& value);
  inline void set_pwd(const char* value);
  inline void set_pwd(const char* value, size_t size);
  inline ::std::string* mutable_pwd();
  inline ::std::string* release_pwd();
  
  // @@protoc_insertion_point(class_scope:protocols.common.PlayerLoginRequest)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_pwd();
  inline void clear_has_pwd();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* pwd_;
  ::google::protobuf::int32 uid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5fclient_2eproto();
  friend void protobuf_AssignDesc_game_5fclient_2eproto();
  friend void protobuf_ShutdownFile_game_5fclient_2eproto();
  
  void InitAsDefaultInstance();
  static PlayerLoginRequest* default_instance_;
};
// -------------------------------------------------------------------

class PlayerLoginResponse : public ::google::protobuf::Message {
 public:
  PlayerLoginResponse();
  virtual ~PlayerLoginResponse();
  
  PlayerLoginResponse(const PlayerLoginResponse& from);
  
  inline PlayerLoginResponse& operator=(const PlayerLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerLoginResponse& default_instance();
  
  void Swap(PlayerLoginResponse* other);
  
  // implements Message ----------------------------------------------
  
  PlayerLoginResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerLoginResponse& from);
  void MergeFrom(const PlayerLoginResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:protocols.common.PlayerLoginResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 error_code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_game_5fclient_2eproto();
  friend void protobuf_AssignDesc_game_5fclient_2eproto();
  friend void protobuf_ShutdownFile_game_5fclient_2eproto();
  
  void InitAsDefaultInstance();
  static PlayerLoginResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// PlayerLoginRequest

// required int32 uid = 1;
inline bool PlayerLoginRequest::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerLoginRequest::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerLoginRequest::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerLoginRequest::clear_uid() {
  uid_ = 0;
  clear_has_uid();
}
inline ::google::protobuf::int32 PlayerLoginRequest::uid() const {
  return uid_;
}
inline void PlayerLoginRequest::set_uid(::google::protobuf::int32 value) {
  set_has_uid();
  uid_ = value;
}

// required string pwd = 2;
inline bool PlayerLoginRequest::has_pwd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayerLoginRequest::set_has_pwd() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayerLoginRequest::clear_has_pwd() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayerLoginRequest::clear_pwd() {
  if (pwd_ != &::google::protobuf::internal::kEmptyString) {
    pwd_->clear();
  }
  clear_has_pwd();
}
inline const ::std::string& PlayerLoginRequest::pwd() const {
  return *pwd_;
}
inline void PlayerLoginRequest::set_pwd(const ::std::string& value) {
  set_has_pwd();
  if (pwd_ == &::google::protobuf::internal::kEmptyString) {
    pwd_ = new ::std::string;
  }
  pwd_->assign(value);
}
inline void PlayerLoginRequest::set_pwd(const char* value) {
  set_has_pwd();
  if (pwd_ == &::google::protobuf::internal::kEmptyString) {
    pwd_ = new ::std::string;
  }
  pwd_->assign(value);
}
inline void PlayerLoginRequest::set_pwd(const char* value, size_t size) {
  set_has_pwd();
  if (pwd_ == &::google::protobuf::internal::kEmptyString) {
    pwd_ = new ::std::string;
  }
  pwd_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerLoginRequest::mutable_pwd() {
  set_has_pwd();
  if (pwd_ == &::google::protobuf::internal::kEmptyString) {
    pwd_ = new ::std::string;
  }
  return pwd_;
}
inline ::std::string* PlayerLoginRequest::release_pwd() {
  clear_has_pwd();
  if (pwd_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = pwd_;
    pwd_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// PlayerLoginResponse

// required int32 error_code = 1;
inline bool PlayerLoginResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerLoginResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerLoginResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerLoginResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 PlayerLoginResponse::error_code() const {
  return error_code_;
}
inline void PlayerLoginResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace protocols

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_5fclient_2eproto__INCLUDED
