# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import game_common_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='game_client.proto',
  package='protocols.common',
  serialized_pb='\n\x11game_client.proto\x12\x10protocols.common\x1a\x11game_common.proto\".\n\x12PlayerLoginRequest\x12\x0b\n\x03uid\x18\x01 \x02(\x05\x12\x0b\n\x03pwd\x18\x02 \x02(\t\")\n\x13PlayerLoginResponse\x12\x12\n\nerror_code\x18\x01 \x02(\x05')




_PLAYERLOGINREQUEST = descriptor.Descriptor(
  name='PlayerLoginRequest',
  full_name='protocols.common.PlayerLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uid', full_name='protocols.common.PlayerLoginRequest.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pwd', full_name='protocols.common.PlayerLoginRequest.pwd', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=104,
)


_PLAYERLOGINRESPONSE = descriptor.Descriptor(
  name='PlayerLoginResponse',
  full_name='protocols.common.PlayerLoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error_code', full_name='protocols.common.PlayerLoginResponse.error_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=106,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['PlayerLoginRequest'] = _PLAYERLOGINREQUEST
DESCRIPTOR.message_types_by_name['PlayerLoginResponse'] = _PLAYERLOGINRESPONSE

class PlayerLoginRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERLOGINREQUEST
  
  # @@protoc_insertion_point(class_scope:protocols.common.PlayerLoginRequest)

class PlayerLoginResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERLOGINRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocols.common.PlayerLoginResponse)

# @@protoc_insertion_point(module_scope)
