# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import error_code_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='game_common.proto',
  package='protocols.common',
  serialized_pb='\n\x11game_common.proto\x12\x10protocols.common\x1a\x10\x65rror_code.proto*;\n\rMessageModule\x12\x13\n\x0fMSG_MODULE_GAME\x10\x00\x12\x15\n\x11MSG_MODULE_SERVER\x10\x0f*O\n\x0bMessageType\x12\x14\n\x10MSG_TYPE_REQUEST\x10\x00\x12\x15\n\x11MSG_TYPE_RESPONSE\x10\x01\x12\x13\n\x0fMSG_TYPE_NOTIFY\x10\x02*N\n\x10ItemPositionType\x12\x0b\n\x07IPT_BAG\x10\x00\x12\r\n\tIPT_EQUIP\x10\x01\x12\r\n\tIPT_DEPOT\x10\x02\x12\x0f\n\x0bIPT_BUYBACK\x10\x03*\x9e\x01\n\rDirectionType\x12\x11\n\rDT_NORTH_WEST\x10\x04\x12\x0c\n\x08\x44T_NORTH\x10\x05\x12\x11\n\rDT_NORTH_EAST\x10\x06\x12\x0b\n\x07\x44T_WEST\x10\x03\x12\x0b\n\x07\x44T_SELF\x10\x00\x12\x0b\n\x07\x44T_EAST\x10\x07\x12\x11\n\rDT_SOUTH_WEST\x10\x02\x12\x0c\n\x08\x44T_SOUTH\x10\x01\x12\x11\n\rDT_SOUTH_EAST\x10\x08*,\n\rMessageAction\x12\x1b\n\x17MSG_ACTION_PLAYER_LOGIN\x10\x01*[\n\x18\x41RENA_PUBLIC_NOTICE_TYPE\x12\x14\n\x10\x41RENA_RANK_TOP_3\x10\x01\x12\x15\n\x11\x41RENA_RANK_TOP_50\x10\x02\x12\x12\n\x0e\x41RENA_CONT_WIN\x10\x03*.\n\x12PUBLIC_NOTICE_TYPE\x12\x18\n\x14SYSTEM_PUBLIC_NOTICE\x10\x00*2\n\nProfession\x12\n\n\x06WIZARD\x10\x01\x12\n\n\x06\x41RCHER\x10\x02\x12\x0c\n\x08SWORDMAN\x10\x03*\x1e\n\x06Gender\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02*<\n\nGameStatus\x12\x0e\n\nGS_OFFLINE\x10\x00\x12\r\n\tGS_ONLINE\x10\x01\x12\x0f\n\x0bGS_FIGHTING\x10\x02*\xaf\x01\n\rAccountStatus\x12!\n\x14\x41\x63\x63ountStatus_BANNED\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n\x15\x41\x63\x63ountStatus_DEFAULT\x10\x00\x12\x1f\n\x1b\x41\x63\x63ountStatus_FIRST_LOGINED\x10\x01\x12\x1f\n\x1b\x41\x63\x63ountStatus_CREATING_ROLE\x10\x02\x12\x1e\n\x1a\x41\x63\x63ountStatus_CREATED_ROLE\x10\x03')

_MESSAGEMODULE = descriptor.EnumDescriptor(
  name='MessageModule',
  full_name='protocols.common.MessageModule',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MSG_MODULE_GAME', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_MODULE_SERVER', index=1, number=15,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=57,
  serialized_end=116,
)


_MESSAGETYPE = descriptor.EnumDescriptor(
  name='MessageType',
  full_name='protocols.common.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE_REQUEST', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE_RESPONSE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_TYPE_NOTIFY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=118,
  serialized_end=197,
)


_ITEMPOSITIONTYPE = descriptor.EnumDescriptor(
  name='ItemPositionType',
  full_name='protocols.common.ItemPositionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='IPT_BAG', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IPT_EQUIP', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IPT_DEPOT', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IPT_BUYBACK', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=199,
  serialized_end=277,
)


_DIRECTIONTYPE = descriptor.EnumDescriptor(
  name='DirectionType',
  full_name='protocols.common.DirectionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DT_NORTH_WEST', index=0, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_NORTH', index=1, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_NORTH_EAST', index=2, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_WEST', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_SELF', index=4, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_EAST', index=5, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_SOUTH_WEST', index=6, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_SOUTH', index=7, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DT_SOUTH_EAST', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=280,
  serialized_end=438,
)


_MESSAGEACTION = descriptor.EnumDescriptor(
  name='MessageAction',
  full_name='protocols.common.MessageAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MSG_ACTION_PLAYER_LOGIN', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=440,
  serialized_end=484,
)


_ARENA_PUBLIC_NOTICE_TYPE = descriptor.EnumDescriptor(
  name='ARENA_PUBLIC_NOTICE_TYPE',
  full_name='protocols.common.ARENA_PUBLIC_NOTICE_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ARENA_RANK_TOP_3', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARENA_RANK_TOP_50', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARENA_CONT_WIN', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=486,
  serialized_end=577,
)


_PUBLIC_NOTICE_TYPE = descriptor.EnumDescriptor(
  name='PUBLIC_NOTICE_TYPE',
  full_name='protocols.common.PUBLIC_NOTICE_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SYSTEM_PUBLIC_NOTICE', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=579,
  serialized_end=625,
)


_PROFESSION = descriptor.EnumDescriptor(
  name='Profession',
  full_name='protocols.common.Profession',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='WIZARD', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARCHER', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SWORDMAN', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=627,
  serialized_end=677,
)


_GENDER = descriptor.EnumDescriptor(
  name='Gender',
  full_name='protocols.common.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=679,
  serialized_end=709,
)


_GAMESTATUS = descriptor.EnumDescriptor(
  name='GameStatus',
  full_name='protocols.common.GameStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GS_OFFLINE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GS_ONLINE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GS_FIGHTING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=711,
  serialized_end=771,
)


_ACCOUNTSTATUS = descriptor.EnumDescriptor(
  name='AccountStatus',
  full_name='protocols.common.AccountStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='AccountStatus_BANNED', index=0, number=-1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AccountStatus_DEFAULT', index=1, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AccountStatus_FIRST_LOGINED', index=2, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AccountStatus_CREATING_ROLE', index=3, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AccountStatus_CREATED_ROLE', index=4, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=774,
  serialized_end=949,
)


MSG_MODULE_GAME = 0
MSG_MODULE_SERVER = 15
MSG_TYPE_REQUEST = 0
MSG_TYPE_RESPONSE = 1
MSG_TYPE_NOTIFY = 2
IPT_BAG = 0
IPT_EQUIP = 1
IPT_DEPOT = 2
IPT_BUYBACK = 3
DT_NORTH_WEST = 4
DT_NORTH = 5
DT_NORTH_EAST = 6
DT_WEST = 3
DT_SELF = 0
DT_EAST = 7
DT_SOUTH_WEST = 2
DT_SOUTH = 1
DT_SOUTH_EAST = 8
MSG_ACTION_PLAYER_LOGIN = 1
ARENA_RANK_TOP_3 = 1
ARENA_RANK_TOP_50 = 2
ARENA_CONT_WIN = 3
SYSTEM_PUBLIC_NOTICE = 0
WIZARD = 1
ARCHER = 2
SWORDMAN = 3
MALE = 1
FEMALE = 2
GS_OFFLINE = 0
GS_ONLINE = 1
GS_FIGHTING = 2
AccountStatus_BANNED = -1
AccountStatus_DEFAULT = 0
AccountStatus_FIRST_LOGINED = 1
AccountStatus_CREATING_ROLE = 2
AccountStatus_CREATED_ROLE = 3



# @@protoc_insertion_point(module_scope)
