# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import game_common_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='stat_data.proto',
  package='protocols.statistics',
  serialized_pb='\n\x0fstat_data.proto\x12\x14protocols.statistics\x1a\x11game_common.proto\"\x94\x01\n\x12PlayerStatBaseInfo\x12\x12\n\x07role_id\x18\x01 \x02(\x05:\x01\x30\x12\x15\n\nprofession\x18\x02 \x01(\x05:\x01\x30\x12\x12\n\x07quality\x18\x03 \x01(\x05:\x01\x30\x12\x15\n\nprof_level\x18\x04 \x01(\x05:\x01\x30\x12\x13\n\x08\x63ur_soul\x18\x05 \x01(\x05:\x01\x30\x12\x13\n\x08max_soul\x18\x06 \x01(\x05:\x01\x30\"\xd2\x04\n\x11\x45quipStrengthInfo\x12\x11\n\x06helmet\x18\x01 \x01(\x05:\x01\x30\x12\x17\n\x0chelmet_level\x18\x02 \x01(\x05:\x01\x30\x12\x13\n\x08necklace\x18\x03 \x01(\x05:\x01\x30\x12\x19\n\x0enecklace_level\x18\x04 \x01(\x05:\x01\x30\x12\x1a\n\x0fshoulder_guards\x18\x07 \x01(\x05:\x01\x30\x12 \n\x15shoulder_guards_level\x18\x08 \x01(\x05:\x01\x30\x12\x10\n\x05\x61rmor\x18\t \x01(\x05:\x01\x30\x12\x16\n\x0b\x61rmor_level\x18\n \x01(\x05:\x01\x30\x12\x14\n\twaistband\x18\x0b \x01(\x05:\x01\x30\x12\x1a\n\x0fwaistband_level\x18\x0c \x01(\x05:\x01\x30\x12\x11\n\x06weapon\x18\r \x01(\x05:\x01\x30\x12\x17\n\x0cweapon_level\x18\x0e \x01(\x05:\x01\x30\x12\x18\n\rassist_weapon\x18\x19 \x01(\x05:\x01\x30\x12\x1e\n\x13\x61ssist_weapon_level\x18\x1a \x01(\x05:\x01\x30\x12\x11\n\x06gloves\x18\x0f \x01(\x05:\x01\x30\x12\x17\n\x0cgloves_level\x18\x10 \x01(\x05:\x01\x30\x12\x15\n\nwrist_band\x18\x11 \x01(\x05:\x01\x30\x12\x16\n\x0bwrist_level\x18\x12 \x01(\x05:\x01\x30\x12\x14\n\tring_1_id\x18\x13 \x01(\x05:\x01\x30\x12\x17\n\x0cring_1_level\x18\x14 \x01(\x05:\x01\x30\x12\x14\n\tring_2_id\x18\x15 \x01(\x05:\x01\x30\x12\x17\n\x0cring_2_level\x18\x16 \x01(\x05:\x01\x30\x12\x10\n\x05shoes\x18\x17 \x01(\x05:\x01\x30\x12\x16\n\x0bshoes_level\x18\x18 \x01(\x05:\x01\x30')




_PLAYERSTATBASEINFO = descriptor.Descriptor(
  name='PlayerStatBaseInfo',
  full_name='protocols.statistics.PlayerStatBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='role_id', full_name='protocols.statistics.PlayerStatBaseInfo.role_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='profession', full_name='protocols.statistics.PlayerStatBaseInfo.profession', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='quality', full_name='protocols.statistics.PlayerStatBaseInfo.quality', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prof_level', full_name='protocols.statistics.PlayerStatBaseInfo.prof_level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cur_soul', full_name='protocols.statistics.PlayerStatBaseInfo.cur_soul', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_soul', full_name='protocols.statistics.PlayerStatBaseInfo.max_soul', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=209,
)


_EQUIPSTRENGTHINFO = descriptor.Descriptor(
  name='EquipStrengthInfo',
  full_name='protocols.statistics.EquipStrengthInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='helmet', full_name='protocols.statistics.EquipStrengthInfo.helmet', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='helmet_level', full_name='protocols.statistics.EquipStrengthInfo.helmet_level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='necklace', full_name='protocols.statistics.EquipStrengthInfo.necklace', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='necklace_level', full_name='protocols.statistics.EquipStrengthInfo.necklace_level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shoulder_guards', full_name='protocols.statistics.EquipStrengthInfo.shoulder_guards', index=4,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shoulder_guards_level', full_name='protocols.statistics.EquipStrengthInfo.shoulder_guards_level', index=5,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='armor', full_name='protocols.statistics.EquipStrengthInfo.armor', index=6,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='armor_level', full_name='protocols.statistics.EquipStrengthInfo.armor_level', index=7,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='waistband', full_name='protocols.statistics.EquipStrengthInfo.waistband', index=8,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='waistband_level', full_name='protocols.statistics.EquipStrengthInfo.waistband_level', index=9,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='weapon', full_name='protocols.statistics.EquipStrengthInfo.weapon', index=10,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='weapon_level', full_name='protocols.statistics.EquipStrengthInfo.weapon_level', index=11,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='assist_weapon', full_name='protocols.statistics.EquipStrengthInfo.assist_weapon', index=12,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='assist_weapon_level', full_name='protocols.statistics.EquipStrengthInfo.assist_weapon_level', index=13,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gloves', full_name='protocols.statistics.EquipStrengthInfo.gloves', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gloves_level', full_name='protocols.statistics.EquipStrengthInfo.gloves_level', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wrist_band', full_name='protocols.statistics.EquipStrengthInfo.wrist_band', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wrist_level', full_name='protocols.statistics.EquipStrengthInfo.wrist_level', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ring_1_id', full_name='protocols.statistics.EquipStrengthInfo.ring_1_id', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ring_1_level', full_name='protocols.statistics.EquipStrengthInfo.ring_1_level', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ring_2_id', full_name='protocols.statistics.EquipStrengthInfo.ring_2_id', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ring_2_level', full_name='protocols.statistics.EquipStrengthInfo.ring_2_level', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shoes', full_name='protocols.statistics.EquipStrengthInfo.shoes', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shoes_level', full_name='protocols.statistics.EquipStrengthInfo.shoes_level', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=806,
)

DESCRIPTOR.message_types_by_name['PlayerStatBaseInfo'] = _PLAYERSTATBASEINFO
DESCRIPTOR.message_types_by_name['EquipStrengthInfo'] = _EQUIPSTRENGTHINFO

class PlayerStatBaseInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERSTATBASEINFO
  
  # @@protoc_insertion_point(class_scope:protocols.statistics.PlayerStatBaseInfo)

class EquipStrengthInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EQUIPSTRENGTHINFO
  
  # @@protoc_insertion_point(class_scope:protocols.statistics.EquipStrengthInfo)

# @@protoc_insertion_point(module_scope)
